# Generated by Django 4.2.30 on 2026-09-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_google_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deletion_nonce',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Makes the account-deletion token single use: it is set when the token is minted and cleared once the deletion is applied.', max_length=64),
        ),
    ]
